Revert "Flatpak: Update base and runtime from 23.08 to 24.08"
This reverts commit 13874a5dd7befcfca3d320ec6083208e66b2a10e.

It seems that the new base image sets certain compile flags that
disallow any build warnings. This results in a failed build of the
argon2 library:

    make: Entering directory '/run/build/threema-desktop/node_modules/argon2/build'
      CC(target) Release/obj.target/libargon2/argon2/src/opt.o
    <command-line>: warning: "_FORTIFY_SOURCE" redefined
    <command-line>: note: this is the location of the previous definition
      CC(target) Release/obj.target/libargon2/argon2/src/argon2.o
    <command-line>: warning: "_FORTIFY_SOURCE" redefined
    <command-line>: note: this is the location of the previous definition
      CC(target) Release/obj.target/libargon2/argon2/src/blake2/blake2b.o
    <command-line>: warning: "_FORTIFY_SOURCE" redefined
    <command-line>: note: this is the location of the previous definition
      CC(target) Release/obj.target/libargon2/argon2/src/core.o
    <command-line>: warning: "_FORTIFY_SOURCE" redefined
    <command-line>: note: this is the location of the previous definition
      CC(target) Release/obj.target/libargon2/argon2/src/encoding.o
    <command-line>: warning: "_FORTIFY_SOURCE" redefined
    <command-line>: note: this is the location of the previous definition
      CC(target) Release/obj.target/libargon2/argon2/src/thread.o
    <command-line>: warning: "_FORTIFY_SOURCE" redefined
    <command-line>: note: this is the location of the previous definition
    rm -f Release/obj.target/argon2.a Release/obj.target/argon2.a.ar-file-list; mkdir -p `dirname Release/obj.target/argon2.a`
    ar crs Release/obj.target/argon2.a @Release/obj.target/argon2.a.ar-file-list
      COPY Release/argon2.a
      CXX(target) Release/obj.target/argon2/argon2.o
    <command-line>: error: "_FORTIFY_SOURCE" redefined [-Werror]
    <command-line>: note: this is the location of the previous definition
    cc1plus: all warnings being treated as errors
    make: *** [argon2.target.mk:152: Release/obj.target/argon2/argon2.o] Error 1
    make: Leaving directory '/run/build/threema-desktop/node_modules/argon2/build'
    Error: `make` failed with exit code: 2
        at ChildProcess.onExit (/run/build/threema-desktop/node_modules/node-gyp/lib/build.js:203:23)
        at ChildProcess.emit (node:events:518:28)
        at ChildProcess._handle.onexit (node:internal/child_process:293:12)

We could try to hunt down the reason for this, but since we plan to use
argon2 through libthreema in the future anyways, we can simply wait
until that has happened before we re-introduce the switch to 24.08.